WIDTH = 70
HEIGHT = 70

LIQUID_MIN = 0.005
LIQUID_MAX = 1.0

COMPRESSION_MAX = 0.25

FLOW_MIN = 0.005
FLOW_MAX = 4.0
FLOW_SPEED = 0.9

SOURCE_LIQUID_PER_ITERATION = 0.2
DRAIN_LIQUID_PER_ITERATION = 0.4

FPS = 300
ADDED_LIQUID_AMOUNT = 1.5

ITERATIONS_PER_FRAME = 3

# --- DISPLAY CONFIG --- #
PIXEL_SIZE = 10

WALL_COLOR = (0, 0, 0)  # black
WATER_COLOR = (173, 216, 230)  # light blue
DARK_WATER_COLOR = (0, 25, 50)  # dark blue
SOURCE_COLOR = (0, 255, 0)
DRAIN_COLOR = (255, 0, 0)

SCREEN_SIZE = [WIDTH * PIXEL_SIZE, HEIGHT * PIXEL_SIZE]

# --- RECORDING CONFIG --- #
RECORDING_OUTPUT_FILE = "output.png"
RECORDING_FREQUENCY = 20
RECORDING_OUTPUT_COLUMNS = 5
